In [16]:
from loadFilteredData import *
#loading all data
origImg = loadAllTopicData('original')
gingham = loadAllTopicData('gingham')
clarendon = loadAllTopicData('clarendon')
juno = loadAllTopicData('juno')
lark = loadAllTopicData('lark')
gotham = loadAllTopicData('gotham')
reyes = loadAllTopicData('reyes')

['abbey', 'airport_terminal', 'amphitheater', 'amusement_park', 'aquarium', 'aqueduct', 'art_gallery', 'assembly_line', 'auditorium']
Loading Topic: abbey
Loading Topic: airport_terminal
Loading Topic: amphitheater
Loading Topic: amusement_park
Loading Topic: aquarium
Loading Topic: aqueduct
Loading Topic: art_gallery
Loading Topic: assembly_line
Loading Topic: auditorium
(9000, 128, 128, 3)
['abbey', 'airport_terminal', 'amphitheater', 'amusement_park', 'aquarium', 'aqueduct', 'art_gallery', 'assembly_line', 'auditorium']
Loading Topic: abbey
Loading Topic: airport_terminal
Loading Topic: amphitheater
Loading Topic: amusement_park
Loading Topic: aquarium
Loading Topic: aqueduct
Loading Topic: art_gallery
Loading Topic: assembly_line
Loading Topic: auditorium
(9000, 128, 128, 3)
['abbey', 'airport_terminal', 'amphitheater', 'amusement_park', 'aquarium', 'aqueduct', 'art_gallery', 'assembly_line', 'auditorium']
Loading Topic: abbey
Loading Topic: airport_terminal
Loading Topic: amphithe

In [17]:
X, y, Xtest, ytest = createData([origImg, clarendon, gingham, juno, lark, gotham, reyes], .8)

9000
9000
9000
9000
9000
9000
9000


In [18]:
X.shape

(50400, 128, 128, 3)

In [19]:
def threeChannelHistogram(images, bins):
    histograms = []
    for image in images:
        redHist = np.histogram(image[:, :, 0], bins=bins, range=(0, 255))[0]
        greenHist = np.histogram(image[:, :, 0], bins=bins, range=(0, 255))[0]
        blueHist = np.histogram(image[:, :, 0], bins=bins, range=(0, 255))[0]
        #print(np.hstack((redHist, greenHist, blueHist)))
        histograms.append(np.hstack((redHist, greenHist, blueHist)))
        #histograms.append(np.histogram(image, bins=bins, range=(0, 255))[0])
    return np.stack(histograms)
bins = 255
categories = 7
Xhist = threeChannelHistogram(X, bins)

In [22]:
from preprocessing import *
import keras
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(32, input_dim=bins * 3, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(categories, activation='softmax'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [23]:
model.fit(Xhist, y, epochs=50, batch_size=256)

Epoch 1/50
50400/50400 [==============================] - 2s 46us/step - loss: 0.3911 - acc: 0.8629
Epoch 2/50
50400/50400 [==============================] - 2s 35us/step - loss: 0.3391 - acc: 0.8720
Epoch 3/50
50400/50400 [==============================] - 2s 34us/step - loss: 0.3168 - acc: 0.8747
Epoch 4/50
50400/50400 [==============================] - 2s 35us/step - loss: 0.2900 - acc: 0.8824
Epoch 5/50
50400/50400 [==============================] - 2s 35us/step - loss: 0.2681 - acc: 0.8953
Epoch 6/50
50400/50400 [==============================] - 2s 35us/step - loss: 0.2551 - acc: 0.9020
Epoch 7/50
50400/50400 [==============================] - 2s 35us/step - loss: 0.2461 - acc: 0.9031
Epoch 8/50
50400/50400 [==============================] - 2s 36us/step - loss: 0.2377 - acc: 0.9036
Epoch 9/50
50400/50400 [==============================] - 2s 35us/step - loss: 0.2293 - acc: 0.9047
Epoch 10/50
50400/50400 [==============================] - 2s 35us/step - loss: 0.2233 - acc: 0.9056

In [26]:
def threeChannelHistogram(images, bins):
    histograms = []
    for image in images:
        redHist = np.histogram(image[:, :, 0], bins=bins, range=(0, 255))[0]
        greenHist = np.histogram(image[:, :, 0], bins=bins, range=(0, 255))[0]
        blueHist = np.histogram(image[:, :, 0], bins=bins, range=(0, 255))[0]
        #print(np.hstack((redHist, greenHist, blueHist)))
        histograms.append(np.hstack((redHist, greenHist, blueHist)))
        #histograms.append(np.histogram(image, bins=bins, range=(0, 255))[0])
    return np.stack(histograms)
from sklearn.metrics import precision_recall_fscore_support
Xhisttest = threeChannelHistogram(Xtest, bins=bins)
predict = model.predict(Xhisttest)
from sklearn.metrics import confusion_matrix
print(confusion_matrix(ytest.argmax(axis=1), predict.argmax(axis=1)))
from sklearn.metrics import accuracy_score
print(accuracy_score(ytest.argmax(axis=1), predict.argmax(axis=1)))
precision_recall_fscore_support(ytest.argmax(axis=1), predict.argmax(axis=1))

[[ 974  146   20  197  299   90   74]
 [ 157 1242    4  311   32   29   25]
 [   2    0 1767    2    0    0   29]
 [ 144  186    5 1130  302    8   25]
 [ 280   22    9  311 1121   12   45]
 [  87   32    1    7    3 1670    0]
 [  10    0   60   19   28    0 1683]]
0.7608730158730159


(array([0.58887545, 0.76289926, 0.94694534, 0.57157309, 0.6280112 ,
        0.92316197, 0.89473684]),
 array([0.54111111, 0.69      , 0.98166667, 0.62777778, 0.62277778,
        0.92777778, 0.935     ]),
 array([0.56398379, 0.72462077, 0.96399345, 0.59835849, 0.62538354,
        0.92546412, 0.91442543]),
 array([1800, 1800, 1800, 1800, 1800, 1800, 1800], dtype=int64))