In [1]:
from loadFilteredData import *

In [3]:
path = 'C:\\Users\\Chunlok Lo\\Documents\\cs4476\\Inverse\\data\\a\\abbey'
filPath = 'C:\\Users\\Chunlok Lo\\Documents\\cs4476\\Inverse\\data\\a_clarendon\\abbey'

origImg, filImg = loadFilteredData(path, filPath)

X, y, Xtest, ytest = createData([origImg, filImg], 0.9)

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
scores = cross_val_score(clf, X.reshape(X.shape[0], -1), y, cv=5)

In [22]:
scores

array([0.625     , 0.625     , 0.64166667, 0.63333333, 0.61666667])

In [24]:
clf.fit(X.reshape(X.shape[0], -1), y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [34]:
from sklearn.metrics import confusion_matrix
predict = clf.predict(Xtest.reshape(Xtest.shape[0], -1))

In [8]:
from sklearn.metrics import accuracy_score
def modelMetric(ytest, predict):
    print(accuracy_score(ytest, predict))
    print(confusion_matrix(ytest.argmax(axis=1), predict.argmax(axis=1), [0, 1]))

In [4]:
def histogramPreprocessing(images, bins=10000):
    histograms = []
    for image in images:
        histograms.append(np.histogram(image, bins=bins, range=(0, 255))[0])
    
    return np.stack(histograms)

def flat(images):
    return images.reshape(images.shape[0], -1)

In [65]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)

In [66]:
Xhist = histogramPreprocessing(X)
clf.fit(Xhist, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [67]:
predict = clf.predict(histogramPreprocessing(Xtest))
modelMetric(ytest, predict)

0.6
[[50 50]
 [30 70]]


In [82]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-5)
clf.fit(histogramPreprocessing(X), y.argmax(axis=1))
predict = clf.predict(histogramPreprocessing(Xtest))
print(accuracy_score(ytest.argmax(axis=1), predict))
print(confusion_matrix(ytest.argmax(axis=1), predict, [0, 1]))

C:\Users\Chunlok Lo\AppData\Local\conda\conda\envs\magiclearning\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.7
[[74 26]
 [34 66]]


In [75]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-5)
clf.fit(flat(X), y.argmax(axis=1))
predict = clf.predict(flat(Xtest))
print(accuracy_score(ytest.argmax(axis=1), predict))
print(confusion_matrix(ytest.argmax(axis=1), predict, [0, 1]))

0.605
[[63 37]
 [42 58]]


C:\Users\Chunlok Lo\AppData\Local\conda\conda\envs\magiclearning\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [7]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(100,100,100), max_iter=500, verbose=10, tol=0.000000001)
clf.fit(histogramPreprocessing(X), y)
predict = clf.predict(histogramPreprocessing(Xtest))
print(accuracy_score(ytest.argmax(axis=1), predict))
print(confusion_matrix(ytest.argmax(axis=1), predict, [0, 1]))


Iteration 1, loss = 10.68991756
Iteration 2, loss = 4.03883867
Iteration 3, loss = 2.85288890
Iteration 4, loss = 2.28455585
Iteration 5, loss = 1.86087413
Iteration 6, loss = 1.73751906
Iteration 7, loss = 1.47639138
Iteration 8, loss = 1.48156056
Iteration 9, loss = 1.41141899
Iteration 10, loss = 1.37037049
Iteration 11, loss = 1.40502707
Iteration 12, loss = 1.30192063
Iteration 13, loss = 1.23829380
Iteration 14, loss = 1.21249953
Iteration 15, loss = 1.14302919
Iteration 16, loss = 1.21423487
Iteration 17, loss = 1.13256238
Iteration 18, loss = 1.12979901
Iteration 19, loss = 1.14656195
Iteration 20, loss = 1.09967422
Iteration 21, loss = 1.23247445
Iteration 22, loss = 1.28246066
Iteration 23, loss = 1.43194293
Iteration 24, loss = 1.42544680
Iteration 25, loss = 1.36839756
Iteration 26, loss = 1.21487036
Iteration 27, loss = 1.09260226
Iteration 28, loss = 1.08751173
Iteration 29, loss = 1.02356330
Iteration 30, loss = 1.02349215
Iteration 31, loss = 1.06318837
Iteration 32, lo

NameError: name 'accuracy_score' is not defined

In [37]:
predict = clf.predict(histogramPreprocessing(Xtest))
print(accuracy_score(ytest, predict))
clf.score(histogramPreprocessing(X), y)

0.66


0.8511111111111112

In [1]:
from loadFilteredData import *
#loading all data
origImg, filImg = loadAllTopicData()
X, y, Xtest, ytest = createData([origImg, filImg], .9)
print(np.sum(y, axis=0))
print(np.sum(ytest, axis=0))

['abbey', 'airport_terminal', 'amphitheater', 'amusement_park', 'aquarium', 'aqueduct', 'art_gallery', 'assembly_line', 'auditorium']
Loading Topic1: abbey
Loading Topic1: airport_terminal
Loading Topic1: amphitheater
Loading Topic1: amusement_park
Loading Topic1: aquarium
Loading Topic1: aqueduct
Loading Topic1: art_gallery
Loading Topic1: assembly_line
Loading Topic1: auditorium
(9000, 128, 128, 3)
(9000, 128, 128, 3)
9000
9000
[8100. 8100.]
[900. 900.]


In [2]:
from preprocessing import *

In [3]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [4]:
# create model
model = Sequential()
model.add(Dense(12, input_dim=10000, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(2, activation='softmax'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [5]:
2
# Fit the model
model.fit(dataHistogram(X, 10000), y, epochs=150, batch_size=128)

Epoch 1/150
16200/16200 [==============================] - 4s 273us/step - loss: 2.0383 - acc: 0.5859
Epoch 2/150
16200/16200 [==============================] - 3s 198us/step - loss: 0.7111 - acc: 0.6264
Epoch 3/150
16200/16200 [==============================] - 3s 186us/step - loss: 0.6693 - acc: 0.6499
Epoch 4/150
16200/16200 [==============================] - 3s 180us/step - loss: 0.6459 - acc: 0.6610
Epoch 5/150
16200/16200 [==============================] - 3s 177us/step - loss: 0.6333 - acc: 0.6660
Epoch 6/150
16200/16200 [==============================] - 3s 176us/step - loss: 0.6126 - acc: 0.6787
Epoch 7/150
16200/16200 [==============================] - 3s 175us/step - loss: 0.6050 - acc: 0.6835
Epoch 8/150
16200/16200 [==============================] - 3s 179us/step - loss: 0.6090 - acc: 0.6835
Epoch 9/150
16200/16200 [==============================] - 3s 181us/step - loss: 0.5910 - acc: 0.6983
Epoch 10/150
16200/16200 [==============================] - 3s 177us/step - loss: 

16200/16200 [==============================] - 3s 179us/step - loss: 0.5126 - acc: 0.7523
Epoch 81/150
16200/16200 [==============================] - 3s 181us/step - loss: 0.5128 - acc: 0.7491
Epoch 82/150
16200/16200 [==============================] - 3s 178us/step - loss: 0.5115 - acc: 0.7499
Epoch 83/150
16200/16200 [==============================] - 3s 179us/step - loss: 0.5084 - acc: 0.7506
Epoch 84/150
16200/16200 [==============================] - 3s 180us/step - loss: 0.5115 - acc: 0.7499
Epoch 85/150
16200/16200 [==============================] - 3s 178us/step - loss: 0.5071 - acc: 0.7562
Epoch 86/150
16200/16200 [==============================] - 3s 182us/step - loss: 0.5151 - acc: 0.7445
Epoch 87/150
16200/16200 [==============================] - 3s 178us/step - loss: 0.5104 - acc: 0.7529
Epoch 88/150
16200/16200 [==============================] - 3s 182us/step - loss: 0.5110 - acc: 0.7531
Epoch 89/150
16200/16200 [==============================] - 3s 177us/step - loss: 0.50

In [7]:
(loss, accuracy) = model.evaluate(dataHistogram(Xtest, 10000), ytest, batch_size=128, verbose=1)

1800/1800 [==============================] - 0s 169us/step


In [8]:
loss

0.4833895152144962

In [9]:
accuracy

0.7877777777777778

In [11]:
predict = model.predict(dataHistogram(Xtest, 10000))

In [12]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(ytest.argmax(axis=1), predict.argmax(axis=1), [0, 1]))


[[674 226]
 [156 744]]


In [73]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(ytest.argmax(axis=1), predict.argmax(axis=1), [0, 1]))


[[883  17]
 [ 71  29]]


In [75]:
from loadFilteredData import *
#loading all data
origImg, filimg = loadAllTopicData()

['abbey', 'airport_terminal', 'amphitheater', 'amusement_park', 'aquarium', 'aqueduct', 'art_gallery', 'assembly_line', 'auditorium']
Loading Topic: abbey
Loading Topic: airport_terminal
Loading Topic: amphitheater
Loading Topic: amusement_park
Loading Topic: aquarium


KeyboardInterrupt: 

In [1]:
from loadFilteredData import *
#loading all data
origImg, filImg = loadAllTopicData()
X, y, Xtest, ytest = createData([origImg, filImg], .9)
print(np.sum(y, axis=0))
print(np.sum(ytest, axis=0))

['abbey', 'airport_terminal', 'amphitheater', 'amusement_park', 'aquarium', 'aqueduct', 'art_gallery', 'assembly_line', 'auditorium']
Loading Topic1: abbey
Loading Topic1: airport_terminal
Loading Topic1: amphitheater
Loading Topic1: amusement_park
Loading Topic1: aquarium
Loading Topic1: aqueduct
Loading Topic1: art_gallery
Loading Topic1: assembly_line
Loading Topic1: auditorium
(9000, 128, 128, 3)
(9000, 128, 128, 3)
9000
9000
[8100. 8100.]
[900. 900.]


In [4]:
from preprocessing import *
import keras
from keras.models import Sequential
from keras.layers import Dense
# create model
model = Sequential()
model.add(Dense(128, input_dim=10000, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(2, activation='softmax'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(dataHistogram(X, 10000), y, epochs=150, batch_size=128)

Epoch 1/150
16200/16200 [==============================] - 4s 255us/step - loss: 8.0165 - acc: 0.4998
Epoch 2/150
16200/16200 [==============================] - 3s 193us/step - loss: 8.0151 - acc: 0.5000
Epoch 3/150
16200/16200 [==============================] - 3s 195us/step - loss: 8.0151 - acc: 0.5000
Epoch 4/150
16200/16200 [==============================] - 3s 202us/step - loss: 8.0151 - acc: 0.5000
Epoch 5/150
10624/16200 [==================>...........] - ETA: 1s - loss: 7.9548 - acc: 0.5038

KeyboardInterrupt: 

In [6]:
Xhistogram = dataHistogram(X, 10000)

In [10]:
model = Sequential()
model.add(Dense(48, input_dim=10000, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(2, activation='softmax'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(Xhistogram, y, epochs=150, batch_size=128)

Epoch 1/150
16200/16200 [==============================] - 3s 208us/step - loss: 6.1833 - acc: 0.5965
Epoch 2/150
16200/16200 [==============================] - 3s 183us/step - loss: 5.9790 - acc: 0.6117
Epoch 3/150
16200/16200 [==============================] - 3s 183us/step - loss: 5.4870 - acc: 0.6353
Epoch 4/150
16200/16200 [==============================] - 3s 184us/step - loss: 5.6521 - acc: 0.6199
Epoch 5/150
16200/16200 [==============================] - 3s 185us/step - loss: 5.4730 - acc: 0.6322
Epoch 6/150
16200/16200 [==============================] - 3s 183us/step - loss: 4.5505 - acc: 0.6570
Epoch 7/150
16200/16200 [==============================] - 3s 186us/step - loss: 1.8320 - acc: 0.6724
Epoch 8/150
16200/16200 [==============================] - 3s 184us/step - loss: 0.6960 - acc: 0.6598
Epoch 9/150
16200/16200 [==============================] - 3s 182us/step - loss: 0.6258 - acc: 0.6871
Epoch 10/150
16200/16200 [==============================] - 3s 182us/step - loss: 

16200/16200 [==============================] - 3s 183us/step - loss: 0.4664 - acc: 0.7844
Epoch 81/150
16200/16200 [==============================] - 3s 206us/step - loss: 0.4761 - acc: 0.7752
Epoch 82/150
16200/16200 [==============================] - 3s 186us/step - loss: 0.4923 - acc: 0.7677
Epoch 83/150
16200/16200 [==============================] - 3s 184us/step - loss: 0.4669 - acc: 0.7832
Epoch 84/150
16200/16200 [==============================] - 3s 183us/step - loss: 0.4730 - acc: 0.7810
Epoch 85/150
16200/16200 [==============================] - 3s 178us/step - loss: 0.4827 - acc: 0.7702
Epoch 86/150
16200/16200 [==============================] - 3s 181us/step - loss: 0.4688 - acc: 0.7839
Epoch 87/150
16200/16200 [==============================] - 3s 202us/step - loss: 0.4644 - acc: 0.7830
Epoch 88/150
16200/16200 [==============================] - 3s 196us/step - loss: 0.4770 - acc: 0.7767
Epoch 89/150
16200/16200 [==============================] - 3s 188us/step - loss: 0.47

In [18]:
model = Sequential()
model.add(Dense(64, input_dim=10000, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(2, activation='softmax'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(Xhistogram, y, epochs=150, batch_size=256)

Epoch 1/150
16200/16200 [==============================] - 3s 200us/step - loss: 6.3718 - acc: 0.5894
Epoch 2/150
16200/16200 [==============================] - 3s 161us/step - loss: 6.1519 - acc: 0.6072
Epoch 3/150
16200/16200 [==============================] - 3s 159us/step - loss: 5.9599 - acc: 0.6181
Epoch 4/150
16200/16200 [==============================] - 3s 162us/step - loss: 5.8574 - acc: 0.6212
Epoch 5/150
16200/16200 [==============================] - 3s 162us/step - loss: 6.0595 - acc: 0.6133
Epoch 6/150
16200/16200 [==============================] - 3s 164us/step - loss: 5.8210 - acc: 0.6270 1s - loss: 5.9212 
Epoch 7/150
16200/16200 [==============================] - 3s 163us/step - loss: 5.8820 - acc: 0.6233
Epoch 8/150
16200/16200 [==============================] - 3s 164us/step - loss: 5.6960 - acc: 0.6280
Epoch 9/150
16200/16200 [==============================] - 3s 163us/step - loss: 5.4733 - acc: 0.6417
Epoch 10/150
16200/16200 [==============================] - 3s 

16200/16200 [==============================] - 3s 164us/step - loss: 0.4523 - acc: 0.7890
Epoch 81/150
16200/16200 [==============================] - 3s 165us/step - loss: 0.4298 - acc: 0.8017
Epoch 82/150
16200/16200 [==============================] - 3s 162us/step - loss: 0.4486 - acc: 0.7892
Epoch 83/150
16200/16200 [==============================] - 3s 165us/step - loss: 0.4366 - acc: 0.7986
Epoch 84/150
16200/16200 [==============================] - 3s 163us/step - loss: 0.4359 - acc: 0.7998
Epoch 85/150
16200/16200 [==============================] - 3s 167us/step - loss: 0.4574 - acc: 0.7881
Epoch 86/150
16200/16200 [==============================] - 3s 160us/step - loss: 0.4243 - acc: 0.8067
Epoch 87/150
16200/16200 [==============================] - 3s 165us/step - loss: 0.4367 - acc: 0.7987
Epoch 88/150
16200/16200 [==============================] - 3s 162us/step - loss: 0.4340 - acc: 0.7975
Epoch 89/150
16200/16200 [==============================] - 3s 163us/step - loss: 0.45

In [21]:
predict = model.predict(dataHistogram(Xtest, 10000))

In [22]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(ytest.argmax(axis=1), predict.argmax(axis=1), [0, 1]))

[[703 197]
 [171 729]]
