In [1]:
from loadFilteredData import *

In [2]:
path = 'C:\\Users\\Chunlok Lo\\Documents\\cs4476\\Inverse\\data\\a\\abbey'
filPath = 'C:\\Users\\Chunlok Lo\\Documents\\cs4476\\Inverse\\data\\a_clarendon\\abbey'

origImg, filImg = loadFilteredData(path, filPath)

X, y, Xtest, ytest = createTrainingData([origImg, filImg], 0.9)

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
scores = cross_val_score(clf, X.reshape(X.shape[0], -1), y, cv=5)

In [22]:
scores

array([0.625     , 0.625     , 0.64166667, 0.63333333, 0.61666667])

In [24]:
clf.fit(X.reshape(X.shape[0], -1), y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [34]:
from sklearn.metrics import confusion_matrix
predict = clf.predict(Xtest.reshape(Xtest.shape[0], -1))

In [63]:
from sklearn.metrics import accuracy_score
def modelMetric(ytest, predict):
    print(accuracy_score(ytest, predict))
    print(confusion_matrix(ytest.argmax(axis=1), predict.argmax(axis=1), [0, 1]))

In [81]:
def histogramPreprocessing(images):
    histograms = []
    for image in images:
        histograms.append(np.histogram(image, bins=10000, range=(0, 255))[0])
    
    return np.stack(histograms)

def flat(images):
    return images.reshape(images.shape[0], -1)

In [65]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)

In [66]:
Xhist = histogramPreprocessing(X)
clf.fit(Xhist, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [67]:
predict = clf.predict(histogramPreprocessing(Xtest))
modelMetric(ytest, predict)

0.6
[[50 50]
 [30 70]]


In [82]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-5)
clf.fit(histogramPreprocessing(X), y.argmax(axis=1))
predict = clf.predict(histogramPreprocessing(Xtest))
print(accuracy_score(ytest.argmax(axis=1), predict))
print(confusion_matrix(ytest.argmax(axis=1), predict, [0, 1]))

C:\Users\Chunlok Lo\AppData\Local\conda\conda\envs\magiclearning\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.7
[[74 26]
 [34 66]]


In [75]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-5)
clf.fit(flat(X), y.argmax(axis=1))
predict = clf.predict(flat(Xtest))
print(accuracy_score(ytest.argmax(axis=1), predict))
print(confusion_matrix(ytest.argmax(axis=1), predict, [0, 1]))

0.605
[[63 37]
 [42 58]]


C:\Users\Chunlok Lo\AppData\Local\conda\conda\envs\magiclearning\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
